{% set version = "1.0.4" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-kedd
  version: {{ version|replace("-", "_") }}

source:
  fn: kedd_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/kedd_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/kedd/kedd_{{ version }}.tar.gz
  sha256: bb944389a61cff22bb3bdde938a0ff6c16700a1ca725ef36b391b97812c45b26

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('kedd')"  # [not win]
    - "\"%R%\" -e \"library('kedd')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=kedd
  license: GPL (>= 2)
  summary: Smoothing techniques and computing bandwidth selectors of the nth derivative of a probability density for one-dimensional data.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - conda-forge/r
