travis:
  secure:
    BINSTAR_TOKEN: iRCXqZ6nhvbSHcm6CXC/q0Rhb7GS0oJuKnLTfwL+8OXRc1MtstcgvR03JQbdZdXpU6Nrg5bThwfQOcMFf2oF9qSJYVxQnHrnwVl36ntFN88zI7/QxrFeHFqTtmX25+WgMEVtPy4CSDp+DX+wIaiPyR+TvgBz81Uj9/BVJlwuiSvBr/l30EWK7UjpMeoKRJrOvl1fKYnMeWL2pjQo89uoXF+muEJk+cOTeDCwCgKoYLjVZJ60aBR7ds7y69m97SWvvwNo7zEekgPonmMmGHHygrG1EvrsFOZ4BHmHSlwmnLIqu1JERNdD7itsYdWjsM+voNTvFRHi20zCbtHrIG+SQMhmK7Weqaplom3R27A7c4Mp9v3WfCa19GkVBoB5is2+UnsdCcGwZ4uKz8fcWAvDeGLziLe8q5z/VC2Nvd8JJpt4jeqxU2aRQ9Ibwkg+Cd2ANOUEs1vEO69hDcRDNOuFO/9abNHFRuovTRiTMQjKBMDyHaV3hT0KIWsqHQ2bwbhrgryUWca8Oiqcw154ZcHhIU5OBRoLbNj6Y15/4a2LtxE6BkKxDF3gKueCcs3RvVihxyI8cpOo3xaKiiwUN8c90JAGJG4nAx1VaUqNZS0r4TQYiSZRnCeap46DAQ/3cyAlknPJ9MuTwN6ze0Q8Uxy3lSzKwWc1Lt5epZjJOLUqFJw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
