appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: KFArM/IiUy6PofcrWMrzaPcPy/RqMfW+jp0J+cxNa7oCMTf6O5Km7IroL9P+wnGZgvuvs3X69bFgFBk9fW2RIMPrhYFml1rQjoBbSZbrQgS5Yg5M/ltmcwj3KVJ56rYJsIKmnECc3wSCzQZAWAlLw+oIXyjEyv+5WSfxHVja+N5c7v+WKM0w9nrwi6mCwhMJUnuIn/KDxLTTip7cAbaXy5jRQIudtVoRIOzsjDRDWLZR57XDdd2zpKIkzkBRTxXRSIRwbx1LTHsPuSDVBhdY/qiFKc+5xCn4myxK43ZdIohDf6/ixuG+VPAMdw8fweJIzufq+UH5Xfb0RkW70bDw3RhJ8hqMPJSrkHINpK8RqkQte+3Qcns3+Pj/P5PYYQ0namajVWz/dRZBsdGe/q8vGCfViWhjrTfpyUHhOZWJyxU9gqsCMlwJQHcln1LOt1TRaD+aAYDWi6D0VJpkPpSTYOSPKpFYIZtZer0ffQSVcKifWL8uvvFL79FsA01VZFjMwNA/nqJ5cv83Sy4LvTOF3GfUKbrWBNU0DQJQeYSx+T8BXfsukagBDKyq+Za9NVJiY9AmeofQDXZUXHts/SU2CKiB6r9oA6B9pO15IvyF2euhzn5TSDGgN4xhEmPHNSL2SVIxd7Nsx7RVuyTSMdRM0tPvkehnDWzZSypssO6hFTw=}
